In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("financial_dataset.csv")

In [4]:
df

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [5]:
df.head()

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00

In [7]:
df.isnull().sum()

Transaction_ID       0
Customer_ID          0
Customer_Name        0
Category            23
Sales               33
Profit              30
Quantity             0
Payment_Status       0
City                21
Transaction_Date     0
dtype: int64

In [8]:
df["Sales"]=df["Sales"].fillna (df["Sales"].mean())

In [9]:
df ["Profit"]=df["Profit"].fillna(df["Profit"].mean())

In [10]:
df["Category"]=df["Category"].fillna(df["Category"].mode()[0])

In [11]:
df["City"]=df["City"].fillna (df["City"].mode()[0])

In [12]:
df.duplicated().sum()

np.int64(40)

In [13]:
df=df.drop_duplicates()

In [14]:
df["Category"]=df["Category"].str.strip().str.title()

C:\Users\Wilson\AppData\Local\Temp\ipykernel_13000\3960893055.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Category"]=df["Category"].str.strip().str.title()

In [15]:
df ["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

C:\Users\Wilson\AppData\Local\Temp\ipykernel_13000\2634966968.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df ["Payment_Status"]=df["Payment_Status"].str.strip().str.title()

In [16]:
df["City"]=df["City"].str.strip().str.title()

C:\Users\Wilson\AppData\Local\Temp\ipykernel_13000\3137970100.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"]=df["City"].str.strip().str.title()

In [17]:
df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"], errors="coerce")
df.dtypes

C:\Users\Wilson\AppData\Local\Temp\ipykernel_13000\2971976620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Transaction_Date"] = pd.to_datetime(df["Transaction_Date"], errors="coerce")

Transaction_ID               int64
Customer_ID                 object
Customer_Name               object
Category                    object
Sales                      float64
Profit                     float64
Quantity                     int64
Payment_Status              object
City                        object
Transaction_Date    datetime64[ns]
dtype: object

In [18]:
print("Cleaned Financial Dataset:")
df

Cleaned Financial Dataset:

,Transaction_ID,Customer_ID,Customer_Name,Category,Sales,Profit,Quantity,Payment_Status,City,Transaction_Date
0,11317,CUST1134,Anjali,Furniture,1875.0,4126.0,16,Pending,Mumbai,2026-10-21 00:00:00
1,11001,CUST1177,Sneha,Stationery,32521.0,9290.0,13,Paid,Bangalore,2026-05-16 00:00:00
2,11069,CUST1478,Sneha,Food,8948.0,8683.0,3,Unpaid,Chennai,2026-06-19 00:00:00
3,11968,CUST1016,Priya,Furniture,20072.0,8320.0,1,Pending,Mumbai,2027-09-11 12:00:00
4,10530,CUST1321,Priya,Stationery,32943.0,9336.0,3,Paid,Bangalore,2025-09-22 12:00:00
...,...,...,...,...,...,...,...,...,...,...
1995,10700,CUST1427,Rahul,Electronics,14407.0,9016.0,8,Paid,Bangalore,2025-12-16 12:00:00
1996,11500,CUST1136,Neha,Electronics,2105.0,5292.0,13,Unpaid,Delhi,2027-01-20 12:00:00
1997,11706,CUST1247,Vivek,Food,35927.0,2756.0,5,Pending,Mangalore,2027-05-03 12:00:00
1998,10511,CUST1299,Rahul,Furniture,48447.0,1654.0,7,Unpaid,Delhi,2025-09-13 00:00:00
1999,11083,CUST1075,Arun,Clothing,8433.0,4718.0,5,Pending,Kochi,2026-06-26 00:00:00

In [20]:
df=pd.read_csv("financial_transactions.csv")

In [21]:
df

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West