In [18]:
import pandas as pd

In [19]:
df=pd.read_csv("financial_transactions.csv")

In [20]:
df

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North
...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West

In [21]:
df.shape

(500, 10)

In [22]:
df.head()

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South
3,4,2026-07-15,Ravi,Grocery,Sugar,5,3430,436,Cash,North
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North

In [23]:
df.describe()

       Transaction_ID    Quantity          Sales        Profit
count      500.000000  500.000000     500.000000     500.00000
mean       250.500000    5.588000   77935.808000   14718.44400
std        144.481833    2.884944  122810.672351   25053.37623
min          1.000000    1.000000     111.000000      11.00000
25%        125.750000    3.000000    6823.250000    1203.75000
50%        250.500000    6.000000   20646.000000    3654.00000
75%        375.250000    8.000000   94242.000000   16099.50000
max        500.000000   10.000000  747490.000000  156830.00000

In [24]:
df["Dae"]=pd.to_datetime(df["Date"])

In [25]:
df.dtypes

Transaction_ID             int64
Date                      object
Customer                  object
Category                  object
Product                   object
Quantity                   int64
Sales                      int64
Profit                     int64
Payment_Method            object
Region                    object
Dae               datetime64[ns]
dtype: object

In [26]:
df[df["Sales"]>6000]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region,Dae
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North,2026-07-08
2,3,2026-05-31,Akhil,Stationery,Pen,9,8181,1051,Cash,South,2026-05-31
4,5,2026-07-26,Meena,Grocery,Rice,6,8748,1861,UPI,North,2026-07-26
5,6,2026-06-08,Neha,Grocery,Rice,9,11250,2952,Net Banking,South,2026-06-08
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West,2026-08-07
...,...,...,...,...,...,...,...,...,...,...,...
495,496,2026-01-20,Priya,Clothing,Jacket,8,15624,4630,Credit Card,North,2026-01-20
496,497,2026-02-03,Priya,Grocery,Rice,7,8351,1690,Net Banking,East,2026-02-03
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North,2026-08-26
498,499,2026-04-02,Rahul,Stationery,Marker,8,13336,2747,Debit Card,South,2026-04-02
499,500,2026-04-17,Swathi,Clothing,Shoes,2,13882,2653,Net Banking,West,2026-04-17

In [27]:
df[df["Profit"]>6000]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region,Dae
0,1,2026-07-08,Anu,Electronics,Laptop,5,167990,21688,Net Banking,North,2026-07-08
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West,2026-08-07
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South,2026-02-23
9,10,2026-01-17,Kiran,Electronics,Smartphone,1,42847,7209,Net Banking,East,2026-01-17
10,11,2026-04-28,Vijay,Clothing,Dress,7,54229,15249,Debit Card,South,2026-04-28
...,...,...,...,...,...,...,...,...,...,...,...
486,487,2026-02-04,Vijay,Furniture,Bookshelf,6,127668,22932,UPI,East,2026-02-04
488,489,2026-03-24,Anu,Clothing,Jeans,9,44496,10356,Debit Card,West,2026-03-24
492,493,2026-07-10,Swathi,Furniture,Bookshelf,2,77646,20985,UPI,South,2026-07-10
494,495,2026-08-22,Neha,Electronics,Headphones,4,238292,62574,Net Banking,South,2026-08-22
497,498,2026-08-26,Ravi,Electronics,Headphones,8,174320,15477,Net Banking,North,2026-08-26

In [28]:
df[df["Transaction_ID"]==8]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region,Dae
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South,2026-02-23

In [29]:
df[(df["Profit"]>6000) & (df["Payment_Method"]=="Cash")]

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region,Dae
6,7,2026-08-07,Sneha,Electronics,Laptop,4,157720,46803,Cash,West,2026-08-07
7,8,2026-02-23,Akhil,Furniture,Bookshelf,6,75954,12261,Cash,South,2026-02-23
30,31,2026-03-17,Kiran,Furniture,Bookshelf,9,305046,34792,Cash,North,2026-03-17
40,41,2026-05-24,Arun,Furniture,Table,8,305232,71804,Cash,North,2026-05-24
42,43,2026-02-23,Sneha,Electronics,Headphones,6,40374,11214,Cash,East,2026-02-23
88,89,2026-03-29,Priya,Electronics,Keyboard,5,315120,58397,Cash,East,2026-03-29
95,96,2026-02-20,Pooja,Clothing,Jacket,10,59160,15195,Cash,South,2026-02-20
109,110,2026-05-10,Akhil,Electronics,Headphones,7,322336,92038,Cash,East,2026-05-10
125,126,2026-04-04,Vijay,Electronics,Laptop,5,296395,25887,Cash,East,2026-04-04
127,128,2026-08-11,Ravi,Clothing,Jacket,8,56848,8239,Cash,West,2026-08-11
134,135,2026-03-02,Neha,Electronics,Headphones,4,238460,42406,Cash,East,2026-03-02
138,139,2026-02-14,Anu,Furniture,Table,3,112209,15164,Cash,South,2026-02-14
169,170,2026-05-29,Swathi,Electronics,Laptop,10,679620,111856,Cash,West,2026-05-29
172,173,2026-03-28,Anjali,Furniture,Sofa,5,136945,23270,Cash,East,2026-03-28
175,176,2026-06-21,Nikhil,Furniture,Desk,7,164689,42638,Cash,West,2026-06-21
182,183,2026-01-27,Nikhil,Furniture,Chair,8,210616,42544,Cash,East,2026-01-27
183,184,2026-02-07,Pooja,Electronics,Smartphone,5,301965,84298,Cash,South,2026-02-07
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West,2026-05-10
198,199,2026-05-13,Akhil,Clothing,Dress,8,28072,7954,Cash,West,2026-05-13
199,200,2026-03-24,Anu,Electronics,Monitor,10,251520,50305,Cash,East,2026-03-24
201,202,2026-07-22,Meena,Furniture,Desk,7,139951,30884,Cash,West,2026-07-22
262,263,2026-04-19,Neha,Furniture,Chair,4,159600,15332,Cash,North,2026-04-19
265,266,2026-07-06,Sneha,Electronics,Smartphone,9,477162,93688,Cash,North,2026-07-06
267,268,2026-07-05,Anu,Furniture,Table,5,71760,20539,Cash,West,2026-07-05
313,314,2026-07-22,Manoj,Furniture,Table,5,60505,14360,Cash,West,2026-07-22
320,321,2026-04-26,Ravi,Furniture,Bookshelf,2,61430,14671,Cash,East,2026-04-26
347,348,2026-06-16,Priya,Furniture,Sofa,2,52738,11928,Cash,West,2026-06-16
364,365,2026-02-02,Akhil,Furniture,Desk,9,170910,19950,Cash,North,2026-02-02
365,366,2026-07-02,Aditya,Furniture,Bookshelf,5,181655,17084,Cash,West,2026-07-02
367,368,2026-05-11,Arun,Furniture,Chair,10,95580,12449,Cash,North,2026-05-11
415,416,2026-07-12,Anu,Furniture,Table,5,194890,18234,Cash,East,2026-07-12
422,423,2026-05-30,Anu,Electronics,Monitor,3,62772,12846,Cash,North,2026-05-30
424,425,2026-06-05,Manoj,Electronics,Smartphone,5,271590,30322,Cash,West,2026-06-05
425,426,2026-08-18,Neha,Furniture,Table,1,33143,9365,Cash,East,2026-08-18
431,432,2026-04-12,Anu,Clothing,Jacket,6,43476,7918,Cash,South,2026-04-12
466,467,2026-06-09,Akhil,Clothing,Jacket,6,46962,8279,Cash,East,2026-06-09
473,474,2026-08-11,Priya,Electronics,Smartphone,9,567090,151646,Cash,West,2026-08-11

In [31]:
df.sort_values("Sales")

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region,Dae
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North,2026-03-01
245,246,2026-08-26,Priya,Grocery,Rice,3,213,62,UPI,West,2026-08-26
217,218,2026-06-14,Aditya,Stationery,Notebook,1,216,19,Debit Card,South,2026-06-14
389,390,2026-02-05,Pooja,Stationery,File,1,229,32,Credit Card,South,2026-02-05
48,49,2026-03-30,Ravi,Stationery,Marker,1,272,57,UPI,North,2026-03-30
...,...,...,...,...,...,...,...,...,...,...,...
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West,2026-05-10
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West,2026-01-05
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West,2026-03-20
169,170,2026-05-29,Swathi,Electronics,Laptop,10,679620,111856,Cash,West,2026-05-29
277,278,2026-02-23,Ravi,Electronics,Smartphone,10,747490,95487,Debit Card,North,2026-02-23

In [32]:
df.sort_values("Profit")

,Transaction_ID,Date,Customer,Category,Product,Quantity,Sales,Profit,Payment_Method,Region,Dae
1,2,2026-03-01,Nikhil,Stationery,File,1,111,11,Net Banking,North,2026-03-01
217,218,2026-06-14,Aditya,Stationery,Notebook,1,216,19,Debit Card,South,2026-06-14
389,390,2026-02-05,Pooja,Stationery,File,1,229,32,Credit Card,South,2026-02-05
48,49,2026-03-30,Ravi,Stationery,Marker,1,272,57,UPI,North,2026-03-30
245,246,2026-08-26,Priya,Grocery,Rice,3,213,62,UPI,West,2026-08-26
...,...,...,...,...,...,...,...,...,...,...,...
157,158,2026-03-20,Meena,Electronics,Headphones,10,652830,127906,Credit Card,West,2026-03-20
287,288,2026-01-05,Arun,Electronics,Keyboard,10,648340,145904,Net Banking,West,2026-01-05
473,474,2026-08-11,Priya,Electronics,Smartphone,9,567090,151646,Cash,West,2026-08-11
191,192,2026-05-10,Swathi,Electronics,Keyboard,9,611964,154833,Cash,West,2026-05-10
298,299,2026-03-25,Arun,Electronics,Headphones,10,534960,156830,Debit Card,West,2026-03-25

In [33]:
df.groupby("Category")[["Sales","Profit"]].sum()

                Sales   Profit
Category
Clothing      2248310   444567
Electronics  22256321  4258542
Furniture    13063762  2399870
Grocery        797596   148153
Stationery     601915   108090

In [34]:
df.groupby("Product")["Sales"].sum()

Product
Biscuits        201050
Bookshelf      2564317
Calculator       80529
Chair          2367729
Cooking Oil     148934
Desk           3749482
Dress           676986
File            177259
Headphones     6651629
Jacket          440538
Jeans           398570
Keyboard       3210209
Laptop         4011847
Marker          120107
Monitor        2561259
Notebook         73943
Pen             150077
Rice            203758
Shirt           473960
Shoes           258256
Smartphone     5821377
Sofa           2264011
Sugar           129337
Table          2118223
Tea             114517
Name: Sales, dtype: int64

In [35]:
df.groupby("Product")[["Sales","Profit"]].sum()

               Sales   Profit
Product
Biscuits      201050    38848
Bookshelf    2564317   422466
Calculator     80529    18107
Chair        2367729   404371
Cooking Oil   148934    30229
Desk         3749482   737419
Dress         676986   134092
File          177259    29767
Headphones   6651629  1281498
Jacket        440538    85255
Jeans         398570    62054
Keyboard     3210209   693752
Laptop       4011847   661193
Marker        120107    20967
Monitor      2561259   496793
Notebook       73943    13938
Pen           150077    25311
Rice          203758    36717
Shirt         473960   107691
Shoes         258256    55475
Smartphone   5821377  1125306
Sofa         2264011   463610
Sugar         129337    25773
Table        2118223   372004
Tea           114517    16586

In [36]:
df.groupby("Product").agg(
Total_Sales=("Sales", "sum"),
Toatl_Profit=("Profit", "sum"),
Toatal_Quantity=("Quantity", "count"))

             Total_Sales  Toatl_Profit  Toatal_Quantity
Product
Biscuits          201050         38848               19
Bookshelf        2564317        422466               25
Calculator         80529         18107               13
Chair            2367729        404371               22
Cooking Oil       148934         30229               19
Desk             3749482        737419               27
Dress             676986        134092               23
File              177259         29767               28
Headphones       6651629       1281498               25
Jacket            440538         85255               22
Jeans             398570         62054               18
Keyboard         3210209        693752               13
Laptop           4011847        661193               19
Marker            120107         20967               17
Monitor          2561259        496793               17
Notebook           73943         13938               17
Pen               150077         25311               19
Rice              203758         36717               29
Shirt             473960        107691               17
Shoes             258256         55475               15
Smartphone       5821377       1125306               23
Sofa             2264011        463610               19
Sugar             129337         25773               20
Table            2118223        372004               21
Tea               114517         16586               13

In [37]:
sales_report=df.groupby("Category").agg(
total_sales=("Sales", "sum"),
total_Profit=("Profit", "sum"),
Toatal_Quantity=("Quantity", "count"))
sales_report

             total_sales  total_Profit  Toatal_Quantity
Category
Clothing         2248310        444567               95
Electronics     22256321       4258542               97
Furniture       13063762       2399870              114
Grocery           797596        148153              100
Stationery        601915        108090               94

In [38]:
df.pivot_table(index="Product",
columns="Region",
values="Sales",
aggfunc="sum")

Region          East    North    South     West
Product
Biscuits       52226    50493     6034    92297
Bookshelf     961756   497082   170050   935429
Calculator     23963    10151     7527    38888
Chair         260080  1189357   472940   445352
Cooking Oil    22207    49822    39713    37192
Desk         1280540   436004   766461  1266477
Dress         111722    59120   311966   194178
File           39960    55165    53980    28154
Headphones    810590  2790210  1235543  1815286
Jacket        111478    51200   111008   166852
Jeans         118516    10086   109434   160534
Keyboard      978893   344474   193608  1693234
Laptop        313071   645424   904350  2149002
Marker         53255    29463    26625    10764
Monitor       598103   295576   847515   820065
Notebook       30017     6169    22893    14864
Pen            51449    46146    15357    37125
Rice           45661    61647    18862    77588
Shirt         139245   108037   110006   116672
Shoes          90286    25500    58095    84375
Smartphone    811130  2023787  1502598  1483862
Sofa          549413   689499   509557   515542
Sugar          16092    36379    49422    27444
Table         403320   465370   480822   768711
Tea            35564    11568    16694    50691